# Generated by Django 4.1.7 on 2023-03-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tort', '0002_delete_city_alter_airport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='IATA код')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
